server:
  port: 84


spring:
  application:
    name: sentinel-nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719

service-url:
  nacos-user-service: http://sentinel-nacos-payment-provider

#对Feign的支持
feign:
  sentinel:
    enabled: true

